name: Build sys-tune and overlay

on: [push]
jobs:
  build:
  
    runs-on: ubuntu-latest
    container: devkitpro/devkita64

    steps:
    - uses: actions/checkout@v1

    - name: Building libnx-Ext
      run: |
        source /etc/profile.d/devkit-env.sh
        make -j$(nproc) -C sys-tune/nxExt

    - name: Building sys-tune
      run: |
        source /etc/profile.d/devkit-env.sh
        API_VERSION=9 make -j$(nproc)
