name: Build sys-tune and overlay

on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install devkitpro
      run: |
        wget https://github.com/devkitPro/pacman/releases/download/v1.0.2/devkitpro-pacman.amd64.deb
        sudo dpkg -i devkitpro-pacman.deb
        sudo dkp-pacman -S switch-dev --noconfirm

    - name: Building libnx-Ext
      run: |
        source /etc/profile.d/devkit-env.sh
        make -j$(nproc) -C sys-tune/nxExt

    - name: Building sys-tune
      run: |
        source /etc/profile.d/devkit-env.sh
        API_VERSION=9 make -j$(nproc)
