name: Build sys-tune and overlay

on: [push]
jobs:
  build:
  
    runs-on: ubuntu-latest
    container: devkitpro/devkita64

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Building libnx-Ext
      run: |
        make -j$(nproc) -C sys-tune/nxExt

    - name: Building sys-tune
      run: |
        API_VERSION=9 make -j$(nproc)

    - name: Print segment size
      run: |
        apt --yes install binutils
        size sys-tune/sys-tune.elf
